###############################################################################
#                          Generated on .docker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: tphello-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=tphello
        - MYSQL_USER=tphello
        - MYSQL_PASSWORD=tphello
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: tphello-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: tphello-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

